#!/bin/sh

CHAN=${1:-0}
if [ -f /dev/rtm_t/aurora0 ]; then
	ASTAT=/dev/rtm_t/aurora0
elif [ -f /dev/rtm-t.0.ctrl/aurora$CHAN ]; then
	ASTAT=/dev/rtm-t.0.ctrl/aurora$CHAN
else
	echo "ERROR channel $CHAN not found"
fi

F0=$(cat $ASTAT)

echo $F0

while [ 1 ]; 
do
	sleep 1
	F1=$(cat $ASTAT)
	if [ "$F1" != "$F0" ]; then
		echo $F1
		echo 0x80 >$ASTAT
		F0=$(cat $ASTAT)
	fi
done

