#!/bin/bash
# runs the example #3.2.2 from RTM-T User Guide
SLOT=${1:-100}
CLKHZ=${CLKHZ:-500000}
CBM=${CBM:-111}

echo setInternalClock ${CLKHZ}
acqcmd -b ${SLOT} setInternalClock ${CLKHZ}
acqcmd -s ${SLOT} set.channelBlockMask ${CBM}
DEV=${SLOT} set.rtm-t dio_bit 3 0
acqcmd -s ${SLOT} set.route d3 in rio out fpga
acqcmd -s ${SLOT} set.trig DI3 rising
acqcmd -b ${SLOT} setMode SOFT_CONTINUOUS 1024
acqcmd -b ${SLOT} setArm

echo -n trigger\>;read STUFF

DEV=${SLOT} set.rtm-t dio_bit 3 1

echo -n stop\>;read STUFF
acqcmd -b ${SLOT} setAbort



