#!/bin/bash

if [ $# -eq 2 ]; then
	echo two args
	exit
fi
let B1=${1:-0}
let B2="($B1 + 1) %66"

echo $B1 $B2

headx() {
	let MX="$1 % 3"
	case $MX in
	0) echo 1-16;;
	1) echo 33-48;; 
	2) echo 17-32;;
	esac	
}

tailx() {
	let MX="$1 % 3"
	case $MX in
	0) echo 1-16;;
	1) echo 33-48;; 
	2) echo 17-32;;
	esac	

}
fdump() {
	HB=$(printf "0.%02d" $1)
	mmap -f $HB | hexdump -e '48/4 "%08x " "\n"'| cut -d\  -f $2
}


stub() {
echo 1-16
fdump $B1 1-16 | tail
echo 17-32
fdump $B1 17-32 | tail
echo 33-48
fdump $B1 33-48 | tail
echo XXXXXXXXXXXXX
}

fdump $B1 $(tailx $B1) | tail
echo -------
fdump $B2 $(headx $B2) | head
